branches:
  only:
  - master
services:
- docker
before_install:
  - docker pull particule/revealjs-builder:stable
  - docker pull particule/wkhtmltopdf:stable
script:
- for dir in styles/* ; do if [ -d "$dir" ] ; then aws s3 cp "$dir".css s3://AWS_S3_BUCKET/formations/revealjs/css/theme/
  && aws s3 cp "$(basename $dir)" s3://$AWS_S3_BUCKET/formations/revealjs/css/theme/"$(basename
  $dir)" --recursive ; fi ; done
- "/bin/bash -x build.sh -l fr"
- "/bin/bash -x build.sh -l en"
deploy:
- provider: s3
  edge: true
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_DEFAULT_REGION"
  acl: public_read
  local_dir: output-html
  upload-dir: formations
- provider: s3
  edge: true
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_DEFAULT_REGION"
  acl: public_read
  local_dir: images
  upload-dir: formations/images
- provider: s3
  edge: true
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_DEFAULT_REGION"
  acl: public_read
  local_dir: output-pdf
  upload-dir: formations/pdf
notifications:
  slack:
    rooms:
    - secure: X7Ji5bYtrLgNy0OsaKs9Ch01KyyuPX0SoBK64AUET72qg3iEfOcSM+MWF2u/Sao4R5kXbUF+Z+op78tC6/o9otyjJdI/xH+4jIOxzWjgyrZNc61kwd8/9MG2Fh2OsJkplA0Fhi8od/CDNjcFbi7SdDzJvX65rdOPTR42dH5PhtDU7TpRs6wYYcV0Q8+seYMkIQbPjptN6mxw+rdiew7Y4UCmvd956gMybsCp72NvQbDP/GxzGnf+7XDkNx8LHfZyrRee2fxnaOlo+jQ/kFagsYRXVMX9nrVzyOiI6b35NBLynmFhSyY0Dv9+Y6QkqAoj9RRjm5hXGg+xHVtfcxxZsJROyly586g9Gzu0n1ZChw8V4WebgDjaVp0U/OGZdeVGxkOO/UUwjgM9z50axxcSK0Sj5902B0v4Kuh45PXbUsI2lSk1JnBaA47nWUScXdRC9LfIq5ykqs4OU/RgG8mo46MSNa6t18dOCkVWIgHJNQPFOGgy6IzUvFwNKemFbL+2wUp2dJ11y9nSAZtdNEL2y/dFmpThLOiDLrLlr8834/BXOlC5ayC8uWkn+swBjv9Fpp0kWww1eBV0Uf6JvoN6irjf32VYCt5GQDjHCRANUrMQT0ATCPeutrJw0Or7atS2jvgkGBwQr2o2amWl5kAs8twkVyC0eNsHfSX9++RZZlA=
    - secure: JTWKe0CU1FFuZ8auuuUqJJVKE/HmeoUf1aY6v6joUszgo7iK4tP8Fswk3nyV4DdmT4kewtRnLp3EbkIMZqPbEae4k1Pd4Mpp9PsjrDkYBUDLKU28V0O9fVu09x3sanN2nJpFU0/9cZnnrPyQFsKHFwgVOrzXbOOiChdKVKKh3cNkZcT4no+cb8Qvc9HJVN/F1V13viBOC5RTnB5yvDQ6ovMVieLTpE4nI5H6wGZlYgJXZQ+oiqCRN38QRG+qbPHPy4xpAnglg9s575ZJLdeiRIYK5vmjRj5bFthRzO/MCjeVVrBXXIrdTRxUmV4w18aEfzgElsjGun3Fp58Pr62giq/FdlhvWFkpVzbHcr8m2X17kF3Pv6ZYQ2wbI6uvX2ZPbh7Xg2Ls1/ox+t8o+4PIoAFea+KirQMADnfyyykkGjxjjxInZyDoVHwwFBZVUmSsIgRg/e83rsMmJ18kuHWN0flWT34yupbSbpltIv2rO9MZ+oBs4dmX0eMYNW84xV12YWxfIWPwm8zNpcILCNVqa4AWRKuqmbYwYzDD/Cf84VV8Bi0OUJqNq5B8uyPq/kklu5gSNnKsmjdSMCFQ1DE+4asjKPqufsYYqwaxPe5A4mWrmCMQP/B5XgGX7wDkBUZ5Eri8WFZHrqg/7TYTzLB5vLEuKt8RSumMm3fB/tmcV/U=
